### ISSUE TITLE
Lowercase for variable names

### ISSUE THREAD

**Issue by haaakon** [meteora8888/swiftTemplates#5]
Have you tried finding if there is a way of making ___Variable_ID___ have a lowercase version also?

For example you want to use the ID as Class Name MyCoordinator, but in the code where it is referenced as a variable you don't want to have uppercase first letter, like this let myCoordinator: MyCoordinator. Do you know if there is way of translating variables to camelCase?

**Comment by andrej-jasso** [comment]
I was thinking of the given example but unfortunately I wasn't able to find an expression how to write it in such way.
Let me know if you were to resolve this issue in some way please :)
